# Generated by Django 5.0.4 on 2024-04-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sedan (Saloon)', 'Sedan (Saloon)'), ('Sport-Utility Vehicle (SUV)', 'Sport-Utility Vehicle (SUV)'), ('Crossover Utility Vehicle (CUV)', 'Crossover Utility Vehicle (CUV)'), ('Pickup Truck)', 'Pickup Truck)'), ('Coupe)', 'Coupe)'), ('Sports Car / Supercar)', 'Sports Car / Supercar)'), ('Hatchback)', 'Hatchback)'), ('Station Wagon (Estate))', 'Station Wagon (Estate))'), ('Convertible)', 'Convertible)'), ('Minivan)', 'Minivan)')], max_length=255)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='media')),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=500)),
                ('drop_off_location', models.CharField(max_length=500)),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('pick_up_time', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.cars')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
