# Generated by Django 5.0.4 on 2024-04-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
