# Generated by Django 5.0.4 on 2024-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0002_cars_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Sedan (Saloon)', 'Sedan (Saloon)'), ('Sport-Utility Vehicle (SUV)', 'Sport-Utility Vehicle (SUV)'), ('Crossover Utility Vehicle (CUV)', 'Crossover Utility Vehicle (CUV)'), ('Pickup Truck', 'Pickup Truck)'), ('Coupe', 'Coupe'), ('Sports Car / Supercar)', 'Sports Car / Supercar)'), ('Hatchback', 'Hatchback'), ('Station Wagon (Estate)', 'Station Wagon (Estate)'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan')], max_length=255),
        ),
    ]
