# Generated by Django 5.0.4 on 2024-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SEDAN_SALOON', 'Sedan (Saloon)'), ('SPORT_UTILITY_VEHICLE_SUV', 'Sport-Utility Vehicle (SUV)'), ('CROSSOVER_UTILITY_VEHICLE_CUV', 'Crossover Utility Vehicle (CUV)'), ('PICKUP_TRUCK', 'Pickup Truck'), ('COUPE', 'Coupe'), ('SPORTS_CAR_SUPERCAR', 'Sports Car / Supercar'), ('HATCHBACK', 'Hatchback'), ('STATION_WAGON_ESTATE', 'Station Wagon (Estate)'), ('CONVERTIBLE', 'Convertible'), ('MINIVAN', 'Minivan')], max_length=255),
        ),
    ]
