# Generated by Django 5.0.4 on 2024-04-30 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0005_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functions', models.CharField(choices=[('AIRCONDITIONS', 'Airconditions'), ('CHILD SEAT', 'Child Seat'), ('GPS', 'GPS'), ('LUGGAGE', 'Luggage'), ('MUSIC', 'Music'), ('SEAT BELT', 'Seat Belt'), ('SLEEPING BED', 'Sleeping Bed'), ('WATER', 'Water'), ('BLUETOOTH', 'Bluetooth'), ('ONBOARD COMPUTER', 'Onboard computer'), ('AUDIO INPUT', 'Audio input'), ('LONG TERM TRIPS', 'Long Term Trips'), ('CAR KIT', 'Car Kit'), ('REMOTE CENTRAL LOCKING', 'Remote central locking'), ('CLIMATE CONTROL', 'Climate control')], max_length=255)),
                ('is_true', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadgets', models.CharField(max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('comment', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.cars')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
