# Generated by Django 5.0.4 on 2024-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0006_features_operations_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='options',
            field=models.CharField(max_length=255, null=tuple),
            preserve_default=tuple,
        ),
    ]
