# Generated by Django 5.0.4 on 2024-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0007_operations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
