# Generated by Django 5.0.4 on 2024-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0008_operations_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='options',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
