# Generated by Django 5.0.4 on 2024-04-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0009_alter_operations_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='car',
        ),
        migrations.AddField(
            model_name='operations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.category'),
        ),
    ]
