# Generated by Django 5.0.4 on 2024-05-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0010_remove_operations_car_operations_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='car',
        ),
        migrations.AddField(
            model_name='features',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.category'),
        ),
    ]
