# Generated by Django 5.0.4 on 2024-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0011_remove_features_car_features_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
