# Generated by Django 5.0.4 on 2024-05-03 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0012_features_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcar',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.cars'),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.category'),
        ),
    ]
