# Generated by Django 5.0.4 on 2024-05-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0014_rentinginstruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentinginstruction',
            name='title',
        ),
    ]
