# Generated by Django 5.0.4 on 2024-05-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0019_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.blog'),
        ),
    ]
