# Generated by Django 5.0.4 on 2024-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0020_blogcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
