# Generated by Django 5.0.4 on 2024-05-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0023_blog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
