# Generated by Django 5.0.4 on 2024-05-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0025_pricing_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='category',
        ),
        migrations.AddField(
            model_name='pricing',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.cars'),
        ),
    ]
