# Generated by Django 5.0.4 on 2024-05-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0026_remove_pricing_category_pricing_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='title_hours',
        ),
    ]
